# This is a basic workflow to help you get started with Actions

name: project2

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install -r requirements.txt
      
      - name: Run unit tests
        run: python -m pytest -v test/*
